/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AlbumsSlugRouteImport } from './routes/albums.$slug'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as RegisterSplatRouteImport } from './routes/register.$'
import { Route as AdminAlbumsIndexRouteImport } from './routes/admin.albums.index'
import { Route as AdminAlbumsSlugRouteImport } from './routes/admin.albums.$slug'
import { Route as AdminAlbumsNewRouteImport } from './routes/admin.albums.new'
import { Route as AdminDebugWasmRouteImport } from './routes/admin.debug.wasm'
import { Route as AdminPhotosPhotoIdRouteImport } from './routes/admin.photos.$photoId'
import { Route as AdminPhotosGeotagRouteImport } from './routes/admin.photos.geotag'
import { Route as AdminPhotosUploadRouteImport } from './routes/admin.photos.upload'
import { Route as AlbumsSlugIndexRouteImport } from './routes/albums.$slug.index'
import { Route as AlbumsSlugMapRouteImport } from './routes/albums.$slug.map'
import { Route as AdminAlbumsSlugAddRouteImport } from './routes/admin.albums_.$slug.add'
import { Route as AdminAlbumsSlugSettingsRouteImport } from './routes/admin.albums_.$slug.settings'
import { Route as AdminAlbumsSlugPhotosPhotoIdRouteImport } from './routes/admin.albums_.$slug.photos.$photoId'
import { Route as ApiIUserIdPhotoIdFileRouteImport } from './routes/api/i.$userId.$photoId.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AlbumsSlugRoute = AlbumsSlugRouteImport.update({
  id: '/albums/$slug',
  path: '/albums/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/login/$',
  path: '/login/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSplatRoute = RegisterSplatRouteImport.update({
  id: '/register/$',
  path: '/register/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlbumsIndexRoute = AdminAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlbumsSlugRoute = AdminAlbumsSlugRouteImport.update({
  id: '/albums/$slug',
  path: '/albums/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlbumsNewRoute = AdminAlbumsNewRouteImport.update({
  id: '/albums/new',
  path: '/albums/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDebugWasmRoute = AdminDebugWasmRouteImport.update({
  id: '/debug/wasm',
  path: '/debug/wasm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosPhotoIdRoute = AdminPhotosPhotoIdRouteImport.update({
  id: '/photos/$photoId',
  path: '/photos/$photoId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosGeotagRoute = AdminPhotosGeotagRouteImport.update({
  id: '/photos/geotag',
  path: '/photos/geotag',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosUploadRoute = AdminPhotosUploadRouteImport.update({
  id: '/photos/upload',
  path: '/photos/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AlbumsSlugIndexRoute = AlbumsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlbumsSlugRoute,
} as any)
const AlbumsSlugMapRoute = AlbumsSlugMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AlbumsSlugRoute,
} as any)
const AdminAlbumsSlugAddRoute = AdminAlbumsSlugAddRouteImport.update({
  id: '/albums_/$slug/add',
  path: '/albums/$slug/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlbumsSlugSettingsRoute = AdminAlbumsSlugSettingsRouteImport.update({
  id: '/albums_/$slug/settings',
  path: '/albums/$slug/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlbumsSlugPhotosPhotoIdRoute =
  AdminAlbumsSlugPhotosPhotoIdRouteImport.update({
    id: '/albums_/$slug/photos/$photoId',
    path: '/albums/$slug/photos/$photoId',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiIUserIdPhotoIdFileRoute = ApiIUserIdPhotoIdFileRouteImport.update({
  id: '/api/i/$userId/$photoId/$file',
  path: '/api/i/$userId/$photoId/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/albums/$slug': typeof AlbumsSlugRouteWithChildren
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/albums/$slug': typeof AdminAlbumsSlugRoute
  '/admin/albums/new': typeof AdminAlbumsNewRoute
  '/admin/debug/wasm': typeof AdminDebugWasmRoute
  '/admin/photos/$photoId': typeof AdminPhotosPhotoIdRoute
  '/admin/photos/geotag': typeof AdminPhotosGeotagRoute
  '/admin/photos/upload': typeof AdminPhotosUploadRoute
  '/albums/$slug/map': typeof AlbumsSlugMapRoute
  '/admin/albums/': typeof AdminAlbumsIndexRoute
  '/albums/$slug/': typeof AlbumsSlugIndexRoute
  '/admin/albums/$slug/add': typeof AdminAlbumsSlugAddRoute
  '/admin/albums/$slug/settings': typeof AdminAlbumsSlugSettingsRoute
  '/admin/albums/$slug/photos/$photoId': typeof AdminAlbumsSlugPhotosPhotoIdRoute
  '/api/i/$userId/$photoId/$file': typeof ApiIUserIdPhotoIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
  '/admin': typeof AdminIndexRoute
  '/admin/albums/$slug': typeof AdminAlbumsSlugRoute
  '/admin/albums/new': typeof AdminAlbumsNewRoute
  '/admin/debug/wasm': typeof AdminDebugWasmRoute
  '/admin/photos/$photoId': typeof AdminPhotosPhotoIdRoute
  '/admin/photos/geotag': typeof AdminPhotosGeotagRoute
  '/admin/photos/upload': typeof AdminPhotosUploadRoute
  '/albums/$slug/map': typeof AlbumsSlugMapRoute
  '/admin/albums': typeof AdminAlbumsIndexRoute
  '/albums/$slug': typeof AlbumsSlugIndexRoute
  '/admin/albums/$slug/add': typeof AdminAlbumsSlugAddRoute
  '/admin/albums/$slug/settings': typeof AdminAlbumsSlugSettingsRoute
  '/admin/albums/$slug/photos/$photoId': typeof AdminAlbumsSlugPhotosPhotoIdRoute
  '/api/i/$userId/$photoId/$file': typeof ApiIUserIdPhotoIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/albums/$slug': typeof AlbumsSlugRouteWithChildren
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/albums/$slug': typeof AdminAlbumsSlugRoute
  '/admin/albums/new': typeof AdminAlbumsNewRoute
  '/admin/debug/wasm': typeof AdminDebugWasmRoute
  '/admin/photos/$photoId': typeof AdminPhotosPhotoIdRoute
  '/admin/photos/geotag': typeof AdminPhotosGeotagRoute
  '/admin/photos/upload': typeof AdminPhotosUploadRoute
  '/albums/$slug/map': typeof AlbumsSlugMapRoute
  '/admin/albums/': typeof AdminAlbumsIndexRoute
  '/albums/$slug/': typeof AlbumsSlugIndexRoute
  '/admin/albums_/$slug/add': typeof AdminAlbumsSlugAddRoute
  '/admin/albums_/$slug/settings': typeof AdminAlbumsSlugSettingsRoute
  '/admin/albums_/$slug/photos/$photoId': typeof AdminAlbumsSlugPhotosPhotoIdRoute
  '/api/i/$userId/$photoId/$file': typeof ApiIUserIdPhotoIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/settings'
    | '/albums/$slug'
    | '/login/$'
    | '/register/$'
    | '/admin/'
    | '/admin/albums/$slug'
    | '/admin/albums/new'
    | '/admin/debug/wasm'
    | '/admin/photos/$photoId'
    | '/admin/photos/geotag'
    | '/admin/photos/upload'
    | '/albums/$slug/map'
    | '/admin/albums/'
    | '/albums/$slug/'
    | '/admin/albums/$slug/add'
    | '/admin/albums/$slug/settings'
    | '/admin/albums/$slug/photos/$photoId'
    | '/api/i/$userId/$photoId/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/settings'
    | '/login/$'
    | '/register/$'
    | '/admin'
    | '/admin/albums/$slug'
    | '/admin/albums/new'
    | '/admin/debug/wasm'
    | '/admin/photos/$photoId'
    | '/admin/photos/geotag'
    | '/admin/photos/upload'
    | '/albums/$slug/map'
    | '/admin/albums'
    | '/albums/$slug'
    | '/admin/albums/$slug/add'
    | '/admin/albums/$slug/settings'
    | '/admin/albums/$slug/photos/$photoId'
    | '/api/i/$userId/$photoId/$file'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/settings'
    | '/albums/$slug'
    | '/login/$'
    | '/register/$'
    | '/admin/'
    | '/admin/albums/$slug'
    | '/admin/albums/new'
    | '/admin/debug/wasm'
    | '/admin/photos/$photoId'
    | '/admin/photos/geotag'
    | '/admin/photos/upload'
    | '/albums/$slug/map'
    | '/admin/albums/'
    | '/albums/$slug/'
    | '/admin/albums_/$slug/add'
    | '/admin/albums_/$slug/settings'
    | '/admin/albums_/$slug/photos/$photoId'
    | '/api/i/$userId/$photoId/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlbumsSlugRoute: typeof AlbumsSlugRouteWithChildren
  LoginSplatRoute: typeof LoginSplatRoute
  RegisterSplatRoute: typeof RegisterSplatRoute
  ApiIUserIdPhotoIdFileRoute: typeof ApiIUserIdPhotoIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/albums/$slug': {
      id: '/albums/$slug'
      path: '/albums/$slug'
      fullPath: '/albums/$slug'
      preLoaderRoute: typeof AlbumsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$': {
      id: '/login/$'
      path: '/login/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$': {
      id: '/register/$'
      path: '/register/$'
      fullPath: '/register/$'
      preLoaderRoute: typeof RegisterSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/albums/': {
      id: '/admin/albums/'
      path: '/albums'
      fullPath: '/admin/albums/'
      preLoaderRoute: typeof AdminAlbumsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/albums/$slug': {
      id: '/admin/albums/$slug'
      path: '/albums/$slug'
      fullPath: '/admin/albums/$slug'
      preLoaderRoute: typeof AdminAlbumsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/albums/new': {
      id: '/admin/albums/new'
      path: '/albums/new'
      fullPath: '/admin/albums/new'
      preLoaderRoute: typeof AdminAlbumsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/debug/wasm': {
      id: '/admin/debug/wasm'
      path: '/debug/wasm'
      fullPath: '/admin/debug/wasm'
      preLoaderRoute: typeof AdminDebugWasmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos/$photoId': {
      id: '/admin/photos/$photoId'
      path: '/photos/$photoId'
      fullPath: '/admin/photos/$photoId'
      preLoaderRoute: typeof AdminPhotosPhotoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos/geotag': {
      id: '/admin/photos/geotag'
      path: '/photos/geotag'
      fullPath: '/admin/photos/geotag'
      preLoaderRoute: typeof AdminPhotosGeotagRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos/upload': {
      id: '/admin/photos/upload'
      path: '/photos/upload'
      fullPath: '/admin/photos/upload'
      preLoaderRoute: typeof AdminPhotosUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/albums/$slug/': {
      id: '/albums/$slug/'
      path: '/'
      fullPath: '/albums/$slug/'
      preLoaderRoute: typeof AlbumsSlugIndexRouteImport
      parentRoute: typeof AlbumsSlugRoute
    }
    '/albums/$slug/map': {
      id: '/albums/$slug/map'
      path: '/map'
      fullPath: '/albums/$slug/map'
      preLoaderRoute: typeof AlbumsSlugMapRouteImport
      parentRoute: typeof AlbumsSlugRoute
    }
    '/admin/albums_/$slug/add': {
      id: '/admin/albums_/$slug/add'
      path: '/albums/$slug/add'
      fullPath: '/admin/albums/$slug/add'
      preLoaderRoute: typeof AdminAlbumsSlugAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/albums_/$slug/settings': {
      id: '/admin/albums_/$slug/settings'
      path: '/albums/$slug/settings'
      fullPath: '/admin/albums/$slug/settings'
      preLoaderRoute: typeof AdminAlbumsSlugSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/albums_/$slug/photos/$photoId': {
      id: '/admin/albums_/$slug/photos/$photoId'
      path: '/albums/$slug/photos/$photoId'
      fullPath: '/admin/albums/$slug/photos/$photoId'
      preLoaderRoute: typeof AdminAlbumsSlugPhotosPhotoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/i/$userId/$photoId/$file': {
      id: '/api/i/$userId/$photoId/$file'
      path: '/api/i/$userId/$photoId/$file'
      fullPath: '/api/i/$userId/$photoId/$file'
      preLoaderRoute: typeof ApiIUserIdPhotoIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlbumsSlugRoute: typeof AdminAlbumsSlugRoute
  AdminAlbumsNewRoute: typeof AdminAlbumsNewRoute
  AdminDebugWasmRoute: typeof AdminDebugWasmRoute
  AdminPhotosPhotoIdRoute: typeof AdminPhotosPhotoIdRoute
  AdminPhotosGeotagRoute: typeof AdminPhotosGeotagRoute
  AdminPhotosUploadRoute: typeof AdminPhotosUploadRoute
  AdminAlbumsIndexRoute: typeof AdminAlbumsIndexRoute
  AdminAlbumsSlugAddRoute: typeof AdminAlbumsSlugAddRoute
  AdminAlbumsSlugSettingsRoute: typeof AdminAlbumsSlugSettingsRoute
  AdminAlbumsSlugPhotosPhotoIdRoute: typeof AdminAlbumsSlugPhotosPhotoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAlbumsSlugRoute: AdminAlbumsSlugRoute,
  AdminAlbumsNewRoute: AdminAlbumsNewRoute,
  AdminDebugWasmRoute: AdminDebugWasmRoute,
  AdminPhotosPhotoIdRoute: AdminPhotosPhotoIdRoute,
  AdminPhotosGeotagRoute: AdminPhotosGeotagRoute,
  AdminPhotosUploadRoute: AdminPhotosUploadRoute,
  AdminAlbumsIndexRoute: AdminAlbumsIndexRoute,
  AdminAlbumsSlugAddRoute: AdminAlbumsSlugAddRoute,
  AdminAlbumsSlugSettingsRoute: AdminAlbumsSlugSettingsRoute,
  AdminAlbumsSlugPhotosPhotoIdRoute: AdminAlbumsSlugPhotosPhotoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlbumsSlugRouteChildren {
  AlbumsSlugMapRoute: typeof AlbumsSlugMapRoute
  AlbumsSlugIndexRoute: typeof AlbumsSlugIndexRoute
}

const AlbumsSlugRouteChildren: AlbumsSlugRouteChildren = {
  AlbumsSlugMapRoute: AlbumsSlugMapRoute,
  AlbumsSlugIndexRoute: AlbumsSlugIndexRoute,
}

const AlbumsSlugRouteWithChildren = AlbumsSlugRoute._addFileChildren(
  AlbumsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlbumsSlugRoute: AlbumsSlugRouteWithChildren,
  LoginSplatRoute: LoginSplatRoute,
  RegisterSplatRoute: RegisterSplatRoute,
  ApiIUserIdPhotoIdFileRoute: ApiIUserIdPhotoIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
