/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotosIndexRouteImport } from './routes/photos.index'
import { Route as AlbumsIndexRouteImport } from './routes/albums.index'
import { Route as RegisterSplatRouteImport } from './routes/register.$'
import { Route as PhotosUploadRouteImport } from './routes/photos.upload'
import { Route as PhotosPhotoIdRouteImport } from './routes/photos.$photoId'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as AlbumsNewRouteImport } from './routes/albums.new'
import { Route as AlbumsSlugRouteImport } from './routes/albums.$slug'
import { Route as AlbumsSlugPhotosPhotoIdRouteImport } from './routes/albums.$slug.photos.$photoId'
import { Route as ApiIUserIdPhotoIdFileRouteImport } from './routes/api/i.$userId.$photoId.$file'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSplatRoute = RegisterSplatRouteImport.update({
  id: '/register/$',
  path: '/register/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosUploadRoute = PhotosUploadRouteImport.update({
  id: '/photos/upload',
  path: '/photos/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosPhotoIdRoute = PhotosPhotoIdRouteImport.update({
  id: '/photos/$photoId',
  path: '/photos/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/login/$',
  path: '/login/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsNewRoute = AlbumsNewRouteImport.update({
  id: '/albums/new',
  path: '/albums/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsSlugRoute = AlbumsSlugRouteImport.update({
  id: '/albums/$slug',
  path: '/albums/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsSlugPhotosPhotoIdRoute = AlbumsSlugPhotosPhotoIdRouteImport.update({
  id: '/photos/$photoId',
  path: '/photos/$photoId',
  getParentRoute: () => AlbumsSlugRoute,
} as any)
const ApiIUserIdPhotoIdFileRoute = ApiIUserIdPhotoIdFileRouteImport.update({
  id: '/api/i/$userId/$photoId/$file',
  path: '/api/i/$userId/$photoId/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/albums/$slug': typeof AlbumsSlugRouteWithChildren
  '/albums/new': typeof AlbumsNewRoute
  '/login/$': typeof LoginSplatRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/photos/upload': typeof PhotosUploadRoute
  '/register/$': typeof RegisterSplatRoute
  '/albums/': typeof AlbumsIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/albums/$slug/photos/$photoId': typeof AlbumsSlugPhotosPhotoIdRoute
  '/api/i/$userId/$photoId/$file': typeof ApiIUserIdPhotoIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/albums/$slug': typeof AlbumsSlugRouteWithChildren
  '/albums/new': typeof AlbumsNewRoute
  '/login/$': typeof LoginSplatRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/photos/upload': typeof PhotosUploadRoute
  '/register/$': typeof RegisterSplatRoute
  '/albums': typeof AlbumsIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/albums/$slug/photos/$photoId': typeof AlbumsSlugPhotosPhotoIdRoute
  '/api/i/$userId/$photoId/$file': typeof ApiIUserIdPhotoIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/albums/$slug': typeof AlbumsSlugRouteWithChildren
  '/albums/new': typeof AlbumsNewRoute
  '/login/$': typeof LoginSplatRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/photos/upload': typeof PhotosUploadRoute
  '/register/$': typeof RegisterSplatRoute
  '/albums/': typeof AlbumsIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/albums/$slug/photos/$photoId': typeof AlbumsSlugPhotosPhotoIdRoute
  '/api/i/$userId/$photoId/$file': typeof ApiIUserIdPhotoIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/albums/$slug'
    | '/albums/new'
    | '/login/$'
    | '/photos/$photoId'
    | '/photos/upload'
    | '/register/$'
    | '/albums/'
    | '/photos/'
    | '/albums/$slug/photos/$photoId'
    | '/api/i/$userId/$photoId/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/albums/$slug'
    | '/albums/new'
    | '/login/$'
    | '/photos/$photoId'
    | '/photos/upload'
    | '/register/$'
    | '/albums'
    | '/photos'
    | '/albums/$slug/photos/$photoId'
    | '/api/i/$userId/$photoId/$file'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/albums/$slug'
    | '/albums/new'
    | '/login/$'
    | '/photos/$photoId'
    | '/photos/upload'
    | '/register/$'
    | '/albums/'
    | '/photos/'
    | '/albums/$slug/photos/$photoId'
    | '/api/i/$userId/$photoId/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AlbumsSlugRoute: typeof AlbumsSlugRouteWithChildren
  AlbumsNewRoute: typeof AlbumsNewRoute
  LoginSplatRoute: typeof LoginSplatRoute
  PhotosPhotoIdRoute: typeof PhotosPhotoIdRoute
  PhotosUploadRoute: typeof PhotosUploadRoute
  RegisterSplatRoute: typeof RegisterSplatRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
  ApiIUserIdPhotoIdFileRoute: typeof ApiIUserIdPhotoIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$': {
      id: '/register/$'
      path: '/register/$'
      fullPath: '/register/$'
      preLoaderRoute: typeof RegisterSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/upload': {
      id: '/photos/upload'
      path: '/photos/upload'
      fullPath: '/photos/upload'
      preLoaderRoute: typeof PhotosUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$photoId': {
      id: '/photos/$photoId'
      path: '/photos/$photoId'
      fullPath: '/photos/$photoId'
      preLoaderRoute: typeof PhotosPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$': {
      id: '/login/$'
      path: '/login/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/new': {
      id: '/albums/new'
      path: '/albums/new'
      fullPath: '/albums/new'
      preLoaderRoute: typeof AlbumsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$slug': {
      id: '/albums/$slug'
      path: '/albums/$slug'
      fullPath: '/albums/$slug'
      preLoaderRoute: typeof AlbumsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$slug/photos/$photoId': {
      id: '/albums/$slug/photos/$photoId'
      path: '/photos/$photoId'
      fullPath: '/albums/$slug/photos/$photoId'
      preLoaderRoute: typeof AlbumsSlugPhotosPhotoIdRouteImport
      parentRoute: typeof AlbumsSlugRoute
    }
    '/api/i/$userId/$photoId/$file': {
      id: '/api/i/$userId/$photoId/$file'
      path: '/api/i/$userId/$photoId/$file'
      fullPath: '/api/i/$userId/$photoId/$file'
      preLoaderRoute: typeof ApiIUserIdPhotoIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AlbumsSlugRouteChildren {
  AlbumsSlugPhotosPhotoIdRoute: typeof AlbumsSlugPhotosPhotoIdRoute
}

const AlbumsSlugRouteChildren: AlbumsSlugRouteChildren = {
  AlbumsSlugPhotosPhotoIdRoute: AlbumsSlugPhotosPhotoIdRoute,
}

const AlbumsSlugRouteWithChildren = AlbumsSlugRoute._addFileChildren(
  AlbumsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AlbumsSlugRoute: AlbumsSlugRouteWithChildren,
  AlbumsNewRoute: AlbumsNewRoute,
  LoginSplatRoute: LoginSplatRoute,
  PhotosPhotoIdRoute: PhotosPhotoIdRoute,
  PhotosUploadRoute: PhotosUploadRoute,
  RegisterSplatRoute: RegisterSplatRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  PhotosIndexRoute: PhotosIndexRoute,
  ApiIUserIdPhotoIdFileRoute: ApiIUserIdPhotoIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
